eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9411

spring:
  application:
    name: zipkin-server

#表示当前程序不使用sleuth
  sleuth:
    enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 556600

  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 556600
    driver-class-name: com.mysql.jdbc.Driver

zipkin:
  storage:
    type: mysql

#spring.sleuth.sampler.percentage: 1.0