eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9411

spring:
  application:
    name: zipkin-server

#表示当前程序不使用sleuth
  sleuth:
    enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 556600

zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200




